### ISSUE TITLE
Grading scheme to be added under the LerarningOpportunityInstance.

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#16]
Grading scheme to be added under the LerarningOpportunityInstance. Either as part of ResultLabel or as a separate tag.

2 different needs:
- Associate a grading scheme to a course with description
- Describe what grading scales are used in the university description

**Comment by wrygiel** [comment]
I guess this requires two new elements/attributes. The first one would be under `<report>`:

```xml
<report>
    ...
    <gradingSchemesUsed>
        <localGradingScheme id="some-local-id">
            Multiline text description.
        </localGradingScheme>
        ...
    </gradingSchemesUsed>
</report>
```

The second one would be under `<learningOpportunityInstance>`. Two ways of doing that:

```xml
<!-- Option 1 -->
<learningOpportunityInstance>
    ...
    <resultLabel localGradingSchemeId="some-local-id">C</resultLabel>
    ...
</learningOpportunityInstance>

<!-- Option 2 -->
<learningOpportunityInstance>
    ...
    <resultLabel>C</resultLabel>
    <localGradingSchemeId>some-local-id</localGradingSchemeId>
    ...
</learningOpportunityInstance>
```

I propose to use the term "local" somewhere in here, to highlight the fact, that these IDs are not standardized. This way, we will (possibly) be able to add a "standard" grading scheme IDs in the future (if there ever will be such a standard, e.g. thanks to Egracons).

The choice between option 1 or 2 seems related to issue #29.

**Comment by wrygiel** [comment]
Option 2 seems better, because it related to multiple elements, not only one:

```xml
<resultGradingSchemeLocalId>some-local-id</resultGradingSchemeLocalId>
<resultLabel>45.1</resultLabel>
<shortenedGrading>
    <percentageLower>62.3</percentageLower>
    <percentageEqual>21.8</percentageEqual>
    <percentageHigher>15.9</percentageHigher>
</shortenedGrading>
<resultDistribution>
    <category count="43" label="Less than 20"/>
    <category count="193" label="20-39.9"/>
    <category count="198" label="40-59.9"/>
    <category count="35" label="60-79.9"/>
    <category count="7" label="80-100"/>
    <description xml:lang="en">Some extra information about the description, might include links etc.</description>
    <description xml:lang="pl">Po polsku...</description>
</resultDistribution>
```

**Comment by wrygiel** [comment]
Also, [this](https://github.com/emrex-eu/elmo-schemas/issues/29#issuecomment-301047652) is a good argument for option 2.

**Comment by wrygiel** [comment]
Staged in `v1.2-preview`. Follow [this thread](https://github.com/emrex-eu/elmo-schemas/issues/37) to see when this is actually released.
