### ISSUE TITLE
Add categories to LearningOpportunitySpecifications.

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#19]
11. Add categories to LearningOpportunitySpecifications.
We need some way of grouping courses. The Type-tag is not sufficient as type should be used only for achieved LearningOpportunitySpecifications. For instance "Bachelor programme" is not an LOS, but it is a category you might want to use.

For example
```xml
<groups> <!-- OPTIONAL 1 -->
 <grouptype id="1"> <!-- REQUIRED 1...* -->
 <title xml:lang="en">Subject</title> <!-- REQUIRED 1...* -->
 <group id="1">
 <title xml:lang="en">Chinese</title> <!-- REQUIRED 1...* --> 
 </group>
 <group id="2">
 <title xml:lang="en">English</title> <!-- REQUIRED 1...* --> 
 </group>
 </grouptype>
 <grouptype id="2">
 <title xml:lang="en">Education plan</title>
 <group id="3">
 <title xml:lang="en">80 group</title> <!-- REQUIRED 1...* --> 
 </group>
 </grouptype>
</groups>
``` 
On LOS level
```xml
<grouping typeref= "1" idref="1" />
<grouping typeref= "2" idref="3" />
```
The title must be in multiple languages. Make it optional. Add some way of sorting

**Comment by wrygiel** [comment]
We also should clearly specify how client developers should handle this in their UIs. There are many "small" questions that need answering, e.g.:

* Should clients use it for ordering, or for labeling items in groups, or both?
* Should clients allow the viewers to pick with grouptype to group with?
* Should clients allow to group by two grouptypes at the same time?
* Is it forbidden to have a single LOS in multiple groups within a single grouptype?
* Why is it on the LOS level, not the LOI level? Is it important?

BTW, I guess that `groupType` fits better with our previous naming style (as opposed to `grouptype`). Other names to consider: `categories/category/categoryItem`.

**Comment by wrygiel** [comment]
How Norway is planning to do this:

1. both.
2. they only use a single group type now, to be discussed.
3. no
4. it should be either `0..1` or `1..1` (to be discussed), but not `0..*` nor `1..*`.
5. probably at the LOI level?

**Comment by richared** [comment]
Update on issue. Please give feedback, or this issue will go in as part of 1.3.

In addition to the original suggestion, we wish to add "sortingKey" on the group-element, to use for sorting. In addition, the grouping tag is suggested moved to LOI.

See https://github.com/emrex-eu/elmo-schemas/tree/issue19

**Comment by janinamincer-daszkiewicz** [comment]
Example.xml: correct indentation in lines 53-56.
XSD:
This part is *very* important, please fill/extend the description in such a way that implementers will have no doubt how to use it
<xs:documentation>Groups...
</xs:documentation>
<xs:complexType name="Groups">
        <xs:annotation>
            <xs:documentation>
                Groups is a way of organizing and sorting over groups of LOI's.
</xs:documentation>

**Comment by geirmv** [comment]
Functionality for grouping courses was introduced to ELMO with version 1.3
