### ISSUE TITLE
Change the description of Academic Term to say that this denotes the academic term when the course was finished /passed / failed

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#20]

**Comment by wrygiel** [comment]
I don't remember discussing this one, and I'm not certain it's a good idea.

* Currently, it "Describes the academic term in which the course took place". So, changing this would be "a bit" backward-incompatible. It wouldn't break anything, but some UIs would treat this academic term as the one in which the course took place. If we change this, then client developers would need to rewrite the label next to which these dates are shown in their UIs.

* Quite often, a student will pass the LOS many months after the LOS is finished (in case of Degree Programmes, this could be years). So this will be much different that the previous meaning. If we need this, then I guess it would be safer to add it as a separate element?

* I suspect this issue might be related to the one about allowing multiple academic terms per LOS (which has been rejected).

**Comment by geirmv** [comment]
Close this issue, it has not come up at a later stage
