### ISSUE TITLE
Agree on a level marking for all levels of education.

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#26]
Agree on a level marking for all levels of education. For instance based on EQF.
Suggestion: Make `<level>` depricated and add `<educationLevel type="EQF">`... Add enumeration for allowed types with description in the XSD, optional description element

**Comment by wrygiel** [comment]
> optional description element

I was the only one voting against it, so I guess it's settled, but still, I will post some arguments against it:

* It's redundant. If we have a clear enumeration and description of each type in the XSD, then including this description *again* in the XML itself might create confusion. Should the developers use the "official" XSD annotations, or should they display the XML descriptions instead?

* Different HEIs might provide very different descriptions for a single level type. If the client displays those, it might confuse the users who might - theoretically - end up comparing them (they might become unsure if these descriptions match the same level type or not).

**Comment by wrygiel** [comment]
You pull request in #35 doesn't include the "optional description element". Can I assume that you're okay with don including it after all?

**Comment by wrygiel** [comment]
Also, this issue talks about deprecating the existing `<level>` element, but your PR is adding a new one, and on a different tree level. Isn't this wrong?

### Solution 1 (your PR)

```xml
<credit>
    <scheme>ects</scheme>
    <level>Bachelor</level>
    <value>6</value>
</credit>
<qualificationLevel type="eqf">5</qualificationLevel>
```

### Solution 2

This is what I understood it was supposed to look like?

```xml
<credit>
    <scheme>ects</scheme>
    <qualificationLevel type="eqf">5</qualificationLevel>
    <value>6</value>
</credit>
```

**Comment by wrygiel** [comment]
Is it on purpose that this new element is `maxOccurs="unbounded"`?

**Comment by wrygiel** [comment]
Ah, the unbounded part is because there are multiple types allowed, I get it.

**Comment by wrygiel** [comment]
@richared1979

**Comment by wrygiel** [comment]
I have pushed a PR based on Solution 2 [here](https://github.com/emrex-eu/elmo-schemas/pull/38).

**Comment by wrygiel** [comment]
This is a much broader and more complex topic. No action here, for now.

**Comment by richared1979** [comment]
A bit of a discussion internally and here is the suggestion:

1: Depricate credit.level
2: Add a level element and make it unbounded:
```xml
<level>
   <type>EQF</type>
   <description>European Qualification Framework</description>
   <value>5</value>
</level>
```

This way, it is possible to describe several types of levels for a LOI.
In the description we should add that only certain types of levels can be expected to be understood by everyone.

**Comment by wrygiel** [comment]
I think that my objections from the [first comment](https://github.com/emrex-eu/elmo-schemas/issues/26#issuecomment-301046267) apply. I don't like it and I think that a clear enumeration would be better (but I was outvoted on this in Oslo).

BTW, is this description supposed to be repeated multiple times, whenever `level` is used? Is it supposed to be lengthy?

**Comment by wrygiel** [comment]
What happens if two different countries start using a single type identifier, for separate levels?

For example, if we had "Polish Qualification Framework", and Portugal would have "Portuguese Qualification Framework", then - in your format - both of us are allowed to use "PQF" as the identifier.

**Comment by mpuzar** [comment]
We discussed this here, for quite a while. If I recall correctly, the idea was to have possibility to add the `countryCode` attribute on the `level` element. That would indicate that it is a local type of level which can be ignored by countries who do not know how to interpret it.

**Comment by wrygiel** [comment]
This doesn't really solve the problem, it just moves it to the country level.

Of course, the chance of a collision on a country level is even smaller, but still, why risk? Why not simply introduce an enumeration? This doesn't need to be an explicit XSD enumeration, we can enumerate "globally supported" values in an annotation, as we did [here](https://github.com/emrex-eu/elmo-schemas/blob/847eeeb7f04ef36a3e02773b5b3de73ec5cd17a5/schema.xsd#L239).

**Comment by richared1979** [comment]
Updated the EQF pull request
