### ISSUE TITLE
Add descriptionHtml with a whitelist of HTML-tags

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#30]

**Comment by wrygiel** [comment]
Note: All current `<description>` elements are of the `PlaintextMultilineStringWithOptionalLang` type, which [explicitly](https://github.com/emrex-eu/elmo-schemas/blob/v1/schema.xsd#L472) forbids HTML. That's why we need a new element if we want LOS descriptions to be formatted.

**Comment by wrygiel** [comment]
Also, since detecting XSS attacks in HTML is quite difficult (one of the top OWASP attack vectors), then we **should not** mark the plaintext `<description>` element as deprecated - many clients might prefer to use this one for security reasons.

**Comment by wrygiel** [comment]
Do we want to whitelist only a certain set of HTML tags? Which set should it be?

If we decide to publish a set of whitelisted tags, then should make following this guideline "required" or "recommended"?

**Comment by wrygiel** [comment]
Norway whitelists the following:

p, br, strong, li, ol, ul

They also replace all header types with strong.

**Comment by wrygiel** [comment]
For the servers: "try to use only the basic tags" (no specifics)
For the clients: "don't trust the server, it can send you XSS"

**Comment by wrygiel** [comment]
Staged in `v1.2-preview`. Follow [this thread](https://github.com/emrex-eu/elmo-schemas/issues/37) to see when this is actually released.
