### ISSUE TITLE
New attachment type "other"

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#32]

**Comment by wrygiel** [comment]
As we discussed, this new attachment type will be added, but - in general - developers should avoid using it. Instead, new attachment types should be added to the official enumeration, whenever needed.

**Comment by wrygiel** [comment]
Staged in `v1.2-preview`. Follow [this thread](https://github.com/emrex-eu/elmo-schemas/issues/37) to see when this is actually released.
