### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by wrygiel** [emrex-eu/elmo-schemas#36]
For a couple of months now, the `master` branch contained unreleased schema changes, and the `v1.2-preview` branch didn't. Also, there's this comment in the README file:

> Please note, that the `master` branch **MAY** contain some changes which has not yet been released (and **MAY** be reverted).

Let's clean this up a bit. From now on, let's try to make the `master` branch contain only the stable changes (which are the changes reviewed and approved by all partners, and officially released under a new version tag). Whereas the unreleased changes (proposals for the new version) will go to `v1.2-preview` branch(es), etc.

As agreed with @richared1979, I'll try to clean this up.

**Comment by wrygiel** [comment]
Just forced a Git update on `master` and `v1.2-preview` branches - in particular these two were forcefully swapped with each other.

**Comment by wrygiel** [comment]
I assume that the changes merged in 7e4d098 are still valid for the `v1.2-preview`.

**Comment by wrygiel** [comment]
My changes introduced a bug: https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/issues/4

I totally forgot that the `v1` branch is part of the XML namespace we officially use and removed it. This fact also means, that we must use `v1` branch instead of the `master` branch, for stable releases.

**Comment by wrygiel** [comment]
I think that the `master` branch should be removed, to avoid confusion (similarly as it has been removed in stable EWP branches).

**Comment by wrygiel** [comment]
@richared1979, also consider making `v1` the default branch. Currently, you made `v1.2-preview` the default branch, so that people visiting this repository see it first. Perhaps it's better for them to see the last accepted version first.

However note, that if `v1` is the default branch, then all pull-requests will go there be default. So, for each pull request you will have to switch its target to `v1.2-preview`.

**Comment by wrygiel** [comment]
I have renamed the `master` branch to `v1`. This should fix issue https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/issues/4.

**Comment by wrygiel** [comment]
> @richared1979, also consider making v1 the default branch. 

@richared1979, please confirm you got that. I don't have permissions to change that.

**Comment by mkurzydlowski** [comment]
@geirmv, @richared1979, have you recently deleted _v1_ branch? I had to reopen an issue in EWP:

https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/issues/4

**Comment by mpuzar** [comment]
Yes, it seems that v1 was taken down as part of a cleanup process. Branches are often short-lived, any references should point to tags. Is there a reason why this cannot be the case here?

**Comment by mkurzydlowski** [comment]
It would be better if @wrygiel answered you question. I assume that he didn't want to link to a specific tag but to the newest version that is backwards compatible with _v1_.

**Comment by wrygiel** [comment]
> I assume that he didn't want to link to a specific tag but to the newest version that is backwards compatible with v1.

Yes. And backward-incompatible changes would be committed to a different branch (`v2`). This way all software that depends on EMREX `v1.x.x` will be able to use the most recent v1 version, without the risk of breaking this software (provided that EMREX will keep using semantic versioning).

**Comment by mpuzar** [comment]
I've now made a new v1 branch based on the current version of v1.4-preview. Does that solve the problem?

**Comment by wrygiel** [comment]
> I've now made a new v1 branch based on the current version of v1.4-preview. Does that solve the problem?

I can't say if that will solve *this particular* problem (it might), but in general, what I had in mind when I created this branch, was something along the lines of EWP `stable-v*` branches:

https://github.com/erasmus-without-paper/ewp-specs-management/tree/v1.2.0#git-branches-and-xml-namespaces

This way, the users will see only the stable and accepted changes in this branch (not a preview of features not yet officially accepted, which could later be withdrawn in a backward-incompatible manner).

BTW, I think it might be useful if EMREX published a similar document stating its backward-compatibility guarantees explicitly (or the lack of thereof), as EWP does. Such transparency is very useful when referencing external schemas.
