### ISSUE TITLE
Release changes from v1.2-preview branch

### ISSUE THREAD

**Issue by wrygiel** [emrex-eu/elmo-schemas#37]
This issue is just a simple reminder that changes from `v1.2-preview` branch need to be eventually merged to `master` branch, and tagged with `v1.2.0` tag.

**Comment by wrygiel** [comment]
There's also an option to release `v1.2.0` **before** we close all the issues. This way, some of the issues will get rescheduled for `v1.3.0`.

Question is, how urgently we want to release the `v1.2-preview` features?

**Comment by wrygiel** [comment]
@richared1979 

All issues **without** the "Help wanted" tag are now merged to `v1.2-preview`. Do we want to release them, or do we want to wait for more issues to be solved first?

**Comment by wrygiel** [comment]
(Waiting for some issues **with** the "Help wanted" tag might mean postponing the release for a couple of months.)

**Comment by geirmv** [comment]
Close this issue, 1.2 has been released.
