### ISSUE TITLE
Requirements to extend ELMO schema for usage by the German “Stiftung für Hochschulzulassung” (SfH)

### ISSUE THREAD

**Issue by GBacharach** [emrex-eu/elmo-schemas#44]
The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.
Current ELMO XML schema release is version 1.4.0. Trying to use this ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:
- Institution-specific characteristic (to be added to the “Issuer” of ELMO-structure)
   - Address
- Person-specific characteristics (to be added to the “Learner” of ELMO-structure)
   - Gender, placeOfBirth, birthName, address
- Certificate-specific characteristics (to be added to the “Learning Opportunity” of ELMO-structure)
   - kind-of-diploma, county-of-acquisition, state-of-acquisition, country-of-acquisition, date-of-acquisition
  - Additionally three grading schemes have to be defined for German HZBs to describe an average grade and a score: 
    - Average grade, 
    - grade in points 300-900
    - grade in points 280-840

**Remarks to the additional institution-specific characteristic:**
SfH needs the address of the diploma issuer to get a unique identification of the issuer (school).

**Remarks to the additional person-specific characteristic:**
SfH needs the diploma learner’s
- gender, placeOfBirth, birthName  and address to search and erase applicants who got more than one account in the SfH application registry (as long as there is no German eID all over)
- gender to address the applicant in digital and analogous letters
- address not to misaddress the applicant in mostly analogous letters.

**Remarks to the certificate-specific characteristics:**
SfH needs the diploma learning-opportunity’s
- kind-of-diploma to verify whether this certificate  qualifies the applicant to study the study program he applies for.
- county-of-acquisition, state-of-acquisition and country-of-acquisition to calculate the compensation between German upper secondary school grades (“Abiturnoten-Ausgleich”)
- date-of-acquisition to 
   - distinguish in winter terms between applicants who already applied in former times and who applies the first time – this data is needed to calculate the date until an applicant is permitted to apply for a study program.
   - calculate the waiting time in the waiting list quota.
- SfH needs at total three grading schemes to describe the grade of a German HZB: The grade can be given either as average grade (1.0, 1.1, …, 4.0), grade in points 300-900 or grade in points 280-840. It is possible, that for special HZBs there is no grade in points but only an average grade given, so it is not always possible to calculate the average grade (out of one grade in points).

**Comment by mpuzar** [comment]
Here are some comments and thoughts from Norway.

> SfH needs the address of the diploma issuer to get a unique identification of the issuer (school).

This should be no problem to add, we just need to agree on a suitable international address format.

> gender, placeOfBirth, birthName and address

Same as above. For gender we propose [ISO/IEC 5218](https://en.wikipedia.org/wiki/ISO/IEC_5218) as used in EWP as well.
Can you please explain a bit birthName? Both first name (`givenNames`) and family name (`familyName`) can be changed during the life, so there might be need for two fields here (or would a concatenated string with the whole name suffice?).

> kind-of-diploma

Here we need some examples - what kind of diplomas are we talking about here? Right now, `learningOpportunityInstance` has a `level` element where you can add the EQF level (1-8). Would that suffice?

> county-of-acquisition, state-of-acquisition and country-of-acquisition to calculate the compensation between German upper secondary school grades (“Abiturnoten-Ausgleich”)

These look like internal requirements that might be potentially best solved with `extension` elements ([see the description in the current schema](https://github.com/emrex-eu/elmo-schemas/blob/v1/schema.xsd#L544)).

> date-of-acquisition

Under `learningOpportunityInstance`, there are `start` (starting date), `date` (end/achieved) and `academicTerm` (with its own `start` and `end`). Don't these fulfill this particular need? Otherwise it looks like an internal requirement that might be best achieved with extension.

> SfH needs at total three grading schemes (...)

If only one of the three schemes is used at a certain point, you can use the `resultLabel` tag, in addition to `gradingScheme` which explains the result. If more than one can be available at the same time, we think an extension is a better solution for this particular need.

**Comment by GBacharach** [comment]
Thank you very much for that fast reply. Here my remarks:

SfH needs the address of the diploma issuer to get a unique identification of the issuer (school).

This should be no problem to add, we just need to agree on a suitable international address format.
Remark: Perfect, please let me know, what address format would suit you.


gender, placeOfBirth, birthName and address

Same as above. For gender we propose ISO/IEC 5218<https://en.wikipedia.org/wiki/ISO/IEC_5218> as used in EWP as well.
Can you please explain a bit birthName? Both first name (givenNames) and family name (familyName) can be changed during the life, so there might be need for two fields here (or would a concatenated string with the whole name suffice?).
Remark:

·         With birthName the family name is meant you got as baby. After marriage family name often is changed, so you need the first family name (“birthName”) as personal identifier. Changes in first name are also possible (if someone changes his or her gender) but not so often, so that we can ignore it for the moment.

·         For gender we can use ISO/IEC 5218 for the moment. In Germany we had some month ago a change in law that you are allowed to get a gender “Diverse” (not male and not female) – but that are exceptions so we can ignore it for the moment (or could “9 – not applicable” used? How are other countries dealing with that?).


kind-of-diploma

Here we need some examples - what kind of diplomas are we talking about here? Right now, learningOpportunityInstance has a level element where you can add the EQF level (1-8). Would that suffice?
Remark: Unfortunately EQF-levels are not enough for our purposes. Especially for diplomas within EQF 4 we need more differentiations:

·         “Allgemeine Hochschulreife”                    The owner has the right to study (in Germany) whatever and wherever he likes

·         “Fachhochschulreife”                                   The owner has the right only to study at universities of applied sciences (colleges)

·         “Fachgebundene Hochschulreife”          The owner has the right only to study special study programs


county-of-acquisition, state-of-acquisition and country-of-acquisition to calculate the compensation between German upper secondary school grades (“Abiturnoten-Ausgleich”)
These look like internal requirements that might be potentially best solved with extension elements (see the description in the current schema<https://github.com/emrex-eu/elmo-schemas/blob/v1/schema.xsd#L544>)

Remark: Sounds suitable. Will you provide me a proposal how to implement this data as extension in the schema?


date-of-acquisition

Under learningOpportunityInstance, there are start (starting date), date (end/achieved) and academicTerm (with its own start and end). Don't these fulfill this particular need? Otherwise it looks like an internal requirement that might be best achieved with extension.
Remark: learningOpportunityInstance/date means the starting date when the diploma starts to be valid („The date on which the student finished studying (may contain a time zone). It doesn't necessarily need to match the end of the academic term. Preferably, this should be the date when the student has passed his final exam.”)? In that case it is exactly what we meant with “date-of-acquisition”.


SfH needs at total three grading schemes (...)

If only one of the three schemes is used at a certain point, you can use the resultLabel tag, in addition to gradingScheme which explains the result. If more than one can be available at the same time, we think an extension is a better solution for this particular need.
Remark: For one diploma there is only one grading scheme available at the same time. So it looks as if your proposal fits (but we would need some help to use it properly).

**Comment by geirmv** [comment]
Conclusion from meeting 8 October 2019:

**Proposal for changes to ELMO 1.5:**

Add the following elements to Learner:
-  gender (ISO-5218)
- placeOfBirth
- birthName
- address

**Proposal for changes to ELMO 2.0:**

Group gradingSchemeLocalId and resultLabel to enable multiple results (for different schemes)

**The following will be handled by extensions:**
Issuer: address
LOS: Kind of diploma
LOS or Issuer: County, State, Country of acquisition
LOI: While waiting for ELMO2.0: Add gradingSchemeLocalId and resultLabel to extension to enable additional grading

**The following will be handled by existing element:**
date-of-acquisition: Use LOI.Date

**Comment by geirmv** [comment]
ELMO meeting 15.12.21: We can move forward to implement following part
- Issuer: Address
- Issuer or (probably) LOS: Country and State (not County)
- Group gradingSchemeLocalId and resultLabel to enable multiple results (for different schemes)

In regard to "Kind of diploma": @GBacharach will check if German National Qualification Framework provide support for this.

**Comment by GBacharach** [comment]
Regarding the requirement "**Group gradingSchemeLocalId and resultLabel to enable multiple results (for different schemes)**"

Please find enclosed an example how this is done currently for German upper secondary school diplomas:
[Thomas_M�ller-M�her_20030516#20210901_161510_sig.txt](https://github.com/emrex-eu/elmo-schemas/files/7814595/Thomas_M.ller-M.her_20030516.20210901_161510_sig.txt)
.

**Comment by GBacharach** [comment]
Regarding the requirement "**Kind of diploma**":

As discussed in the ELMO workshop on 15.12.2021: In the context of the German requirements, how the different German upper secondary school education certificates can be mapped in the ELMO data structure. In doing so, I am repeatedly referred to the EQF attribute, which, however, from my point of view, does not have precisely this differentiation in EQF level 4, even at the German national level (see https://www.cedefop.europa.eu/files/germany_-_european_inventory_on_nqf_2018.pdf page 13):

- Upper secondary general education school leaving certificate (Allgemeine Hochschulreife (AHR))
- Qualification entitling holder to study particular subjects at a higher education institution (Fachgebundene Hochschulreife (FgbHR))
- Qualification entitling holder to study at a university of applied sciences (Fachhochschulreife (FHR))
- Dual VET (three-year and three-and-a-half-year training courses)
- Full-time vocational school (regulated under Länder law) (Berufsfachschule)
- Full vocational qualification (full-time vocational school) (Berufsfachschule)

ELM (or EDCI) should have the same problem (EQF or NQF as attribute of "qualification").

Do I see it correctly that we need an extension of the two standards here so that we can automatically assign the digital HZBs? Or am I missing something?

**Comment by GBacharach** [comment]
Requirement on "**Country and State**"

We need that data fields on LOS level, because it is possible that country and state of aquirement is different to the location of the issuing school.

Additionally we need currently help in mapping County, State, Country of acquisition to ELMO LOS. That is missing in the diplomas we are using in our German field tests.
