### ISSUE TITLE
Cant generate classes from schema

### ISSUE THREAD

**Issue by dosjos** [emrex-eu/elmo-schemas#49]
Hi
I'm trying to generate classes (with xsd.exe) from your schema version 1.5, but it does not work, I get the following error:
- The datatype 'https://github.com/erasmus-without-paper/ewp-specs-types-address/tree/stable-v1:FlexibleAddress' is missing.

And i cant find that datatype in any of the files in the zip package
![image](https://user-images.githubusercontent.com/609086/74731186-d0f38f80-5247-11ea-9818-5e454c30c8d0.png)

**Comment by mpuzar** [comment]
The ELMO schema refers to the source on github (line 13) which does exist, maybe you need to download it locally (like you did with Europass and XML-DSig) for your class generator to work?

**Comment by dosjos** [comment]
Thanks, that worked :)
