### ISSUE TITLE
Include a bug-reporting email in NCP response

### ISSUE THREAD

**Issue by wrygiel** [emrex-eu/elmo-schemas#5]
After EMREX is finalized and external developers start to use it, how should such external developers request support and/or report bugs to the NCP developers?

Perhaps it would be a good idea to include an NCP developer contact email within the ELMO itself? E.g.

``` xml
<elmo>
    ...
    <ncpDeveloperContact>
        <email>usos@usos.edu.pl</email>
    </ncpDeveloperContact>
    ...
</elmo>
```

It's just a suggestion. I will not pursue this issue unless some other developers +1 on this.

**Comment by emrex-eu** [comment]
I agree, except for the ncp part, make it non-EMREX

**Comment by wrygiel** [comment]
Currently, I believe that EMREG would be a better place for such addresses (as opposed to putting it directly in the ELMO file).
