### ISSUE TITLE
Please add a licence to schema.xsd

### ISSUE THREAD

**Issue by bwhpers** [emrex-eu/elmo-schemas#53]

**Comment by geirmv** [comment]
Initial discussion in the EMREX Executive Committee, A license should be added to ELMO for next version. E g use the same license as for EWP - where a MIT license has been added. Will probably be added for ELMO 1.7.
(also included in EDSSI task 2.2)

**Comment by geirmv** [comment]
Text for contributor page;

Beneficiaries of the EMREX grant agreement No 2014 – 3656/001-001,

EMREX run throughout 2015 and 2017:

CSC – IT Center for Science Ltd, Finland
Ministry of Higher Education and Science (Uddannelses- og Forskningsministeriet), Denmark
Kion, Italy
University of Oslo (Universitetet i Oslo), Norway
University of Warsaw (Uniwersytet Warszawski), Poland
the Ladok Consortium, Sweden
Swedish Council for Higher Education (UHR), Sweden
Umeå University (Umeå Universitet), Sweden
