### ISSUE TITLE
Make identifier local required

### ISSUE THREAD

**Issue by bhellstrom** [emrex-eu/elmo-schemas#54]
Ladok in Sweden has for some time been handling elmo automatically to create qualifications useful for a student in the national system. 

We have seen problems with that LearningOpportunitySpecification identifier "local" is not a mandatory to set. Our automatic handling can therefore when the attribute "local" is missing not automatically handle the course in our system in the way we want.

Therefor we wish that it would be mandatory to set a least one predefined type

**Comment by geirmv** [comment]
ELMO meeting 15.12.21: We can move forward to implement this as a recommendation (in the schema documentation for LOS id)

**Comment by mirkostanic** [comment]
Implemented in V2.0
