### ISSUE TITLE
Use of Publications Office authority table URIs to increase interoperability with SDG, Europass and others

### ISSUE THREAD

**Issue by init-xbildung** [emrex-eu/elmo-schemas#57]
From the German XBildung project [we](https://xbildung.de/web/) have the following proposal 
regarding the encoding of countries and other codes  (ISCED2013, EQF/NQF, ISCED 2013) in future ELMO versions  
for the sake of enhanced interoperability and reuse of multilingual ressources in Europe.

**Context:**
ELMO refers to "an Europass" ISO Country Code list under the namespace http://europass.cedefop.europa.eu/Europass/V2.0

Other emerging standards like the SDG-Datamodels or the current Europass Learning Model refer to Publications Office Country code list instead:  https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country

**Example**:
Germany instead of 
  `  <country>DE</country>`
could also be referred to as  
    `<country>http://publications.europa.eu/resource/authority/country/DEU</country>`

Poland instead of "PL" can be referred to 
`    <country>PL</country>`
could also be referred to as  
  `  <country>http://publications.europa.eu/resource/authority/country/POL</country>`

In doing so the data exchange interoperability specifications SDG and Europass benefit from the following features:

**reasonings for changing** to a new country code lists (still the same ISO 3166)
1. active governance and redistribution by EU Publications Office in different formats, _see https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country for more information_
2. existing namespace, the namespace "http://europass.cedefop.europa.eu/Europass/V2.0" became outdated to our understanding long time ago - when governance for Europass shifted from CEDEFOP to DG EMPL - when Publications Office started publishing Europass vocabularies here https://op.europa.eu/en/web/eu-vocabularies/europass 
3. can express European realities like Kosovo or former countries like http://publications.europa.eu/resource/authority/country/DDR or other countries not being able to be expressed via the current ELMO "Europass ISO List" 
4. using URIs instead of values can bring all ELMO users the translation of country names in all EU languages![image](https://user-images.githubusercontent.com/99474274/169386844-d42a0dea-4ffb-4dc2-9a24-1a6b266f468a.png) 
see here for http://publications.europa.eu/resource/authority/country/POL and http://publications.europa.eu/resource/authority/country/DEU

5. the country code list from PO is used in other education specifications to express educational credentials like 

- the future SDG data models 
see admin unit level 1 from ISA Core Vocabularies Location
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables.md
![image](https://user-images.githubusercontent.com/99474274/169387015-7b543c35-5265-40db-8170-6fa099b9f11b.png)

- Europass see https://github.com/european-commission-empl/European-Learning-Model/blob/master/Europass_Learning_Model.md#location (

![image](https://user-images.githubusercontent.com/99474274/169387910-66d326dd-f8b1-4be0-bf89-a225eb457bbf.png)
)

So the proposal is here 
to enhance european interoperability of ELMO 
by expressing countries (and perhaps citizenships) 
using the Publications Office country code list in form of using the concept URIs. 
It bears the same two-digit ISO information but comes with the features described above.

Please not that the same benefits are true for the following Publications Office code lists currently used in ELMO as "strings" instead of URIs:
a) EQF/DQF  http://data.europa.eu/snb/eqf/25831c2
b) languages https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/language 
c) ISCED-F 2013 https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/international-education-classification

Sebastian from [XBildung.de](http://www.XBildung.de?ref=ELMO) (SDG and online access act standardisation in Germany for school and higher education)

**Comment by mirkostanic** [comment]
Using URIs can lead to link rot. With developments around ELM it is felt that ELMO would be better utilised by serving a more international audience than only EU.
