### ISSUE TITLE
Express language skills with the Common European Reference Framework for Languages

### ISSUE THREAD

**Issue by init-xbildung** [emrex-eu/elmo-schemas#58]
In Germany currently ELMO is also piloted to encode **secondary education diplomas** like the "Abiturzeugnis" within the project "Digitales Schulzeugnis". https://www.digiz.nrw/was-ist-das-digitale-zeugnis 

The Abiturzeugnis in Germany shows some differences to higher education diplomas. 
Some of the differences could be considered for a future evolution of ELMO in case ELMO usage is intended also for primary and secondary education diplomas in EU Member States:

One aspect is "how to express language levels"

In the German Abiturzeugnis and elsewhere for the sake of European interoperability of Member States credentials the language level has to be expressed using the Common Reference Framework for Languages of the Council of Europe.
https://www.coe.int/en/web/common-european-framework-reference-languages 

Example:
instead of saying in ELMO for a course (LOS) in "English"
` <title xml:lang="en">English</title>` being passed with 
```
 <gradingSchemeLocalId>0-100</gradingSchemeLocalId>
                    <resultLabel>45.1</resultLabel>
```
one could better say in addition 
```
 <gradingSchemeInternationalId>CEFR</gradingSchemeLocalId>
 <resultLabel>C1</resultLabel>
```

More information on CEFR: 
https://www.coe.int/en/web/common-european-framework-reference-languages

Please note also our initiative to get the CEFR as an Publications Office Taxonomy via Europass https://github.com/european-commission-empl/European-Learning-Model/issues/44

**Comment by mirkostanic** [comment]
Added in V2.0
