### ISSUE TITLE
Align name types and birth information about the learner with ISA Core Person or eIDAS minimum data set

### ISSUE THREAD

**Issue by init-xbildung** [emrex-eu/elmo-schemas#59]
ELMO V1.6 refers to 

- ISO/IEC 5218 code of human gender 
not answering the need to express "non-binary genders", 
see some discussions on this here https://github.com/SEMICeu/Core-Person-Vocabulary/issues/38  or https://github.com/SEMICeu/Core-Person-Vocabulary/issues/7

- has a (V1.5 from 2019) [added ](https://github.com/emrex-eu/elmo-schemas/issues/44)property called "b**day**" to express **Date** of Birth

- puts birthplace information (place, country) of the learner in a single string `placeOfBirth`

At the same time a more standardised way exist with the ISA Core Vocabularies https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/e-government-core-vocabularies/release/200-0 to express 
Natural Persons and the different name types and birth (and death information) 

The ISA Core vocabulary Person features concepts like CountryOfBirth AND PlaceOfBirth  has a DateOfBirth and different "name" concepts including matronymic and patronymic names and alternative representation of names.
https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/html/overview.jpg
![image](https://user-images.githubusercontent.com/99474274/169408883-d6de2fc4-8273-47f1-9948-ede7e9db75f4.png)

Another orientation point could be the eIDAS minimum attributes on persons that will a Higher education institution will get in future in a request in the SDG article 14 system.
http://mapping.semic.eu:81/vdm/about/html/http%3A%2F%2Fmapping.semic.eu%2Fvdm%2Fid%2Fcv%2Feb004434a93bbeaa2ba5968d26af06be

![image](https://user-images.githubusercontent.com/99474274/169410929-d621f3c2-5b1f-4916-a828-773f6b9b8f4b.png)

For the sake of a EU interoperable ELMO 2.X being kind of aligned with SDG, Europass and other European data exchanges we suggest to align existing and future ELMO 
a) element names
b) data types
c) and descriptions 
towards ISA Core Vocabularies or towards other Interoperability standards when it comes to express information on the (European) learner.

The following actions would be needed for an alignement to the ISA Core Vocabulary Person:
- rename bday -> DayOfBirth
- rename givenNames -> givenName
- add countryOfBirth 
- add fullname
- add alternative name
- change ISO-Gender to Publications Office gender code lists

**Comment by mirkostanic** [comment]
With eIDAS 2 directive in it's final stages it would be prudent to wait to see if there will be any changes in the eIDAS minimum dataset.

**Comment by mirkostanic** [comment]
Implemented in V2.0
