### ISSUE TITLE
Courses may span across multiple academic terms

### ISSUE THREAD

**Issue by wrygiel** [emrex-eu/elmo-schemas#6]
On Thu, Dec 3, 2015 at 3:46 PM, Salum Abdul-Rahman wrote:

> As a developer it would preferable for us if a course covering multiple terms would have multiple instances of the academicTerm-entity instead of on entity with cardinality expressed in the content. I know this is too late to for you include in version 1.0, but please keep it in mind for future revision.

On Fri, Dec 4, 2015 at 11:18 AM, Wojtek Rygielski wrote:

> Does this mean that in Finland you have courses which span across
> multiple academic terms?
> 
> In Poland one course is always bound to a single academic term.

On Fri, Dec 4, 2015 at 11:33 AM, Matija Puzar wrote:

> The same applies to Norway - one course can indeed span over multiple
> academic terms. The system must allow for this.

**Comment by wrygiel** [comment]
BTW: Changing `maxOccurs` on `academicTerm` would be a backward-incompatible change, so this would require 2.0.0 revision.

**Comment by emrex-eu** [comment]
Closed, not approved by ELMO group
