### ISSUE TITLE
Differentiate different types of courses and include information about courses being taken into account for the final grade

### ISSUE THREAD

**Issue by init-xbildung** [emrex-eu/elmo-schemas#61]
In the German project "digitales Schulzeugnis" ELMO v1.6 is used to encode credentials of the secondary education in ELMO:

The following information can currently not be encoded in a machine readable structured way with the ELMO V1.6 Version. 
Do you have any proposals how to encode it better - without using the generic "resultLabel" or could you imagine introducing new attributes for this?

1. Differentiate type (intensity of courses: especially "Leistungskurs" from "Grundkurs" from "Facharbeit" currently meshed-up in the `title` of a course or in `resultlabel`

1. Say that a result was taken into account to calculate the overall grade, currently encoded with a German string "eingebracht" in `resultlabel`

(in the ELMO-usage of the German Abiturzeugnis also grades that were not taken into account for the overall grade shell be listed)

**Comment by mirkostanic** [comment]
This can be placed into extension by directly copying the XSD schema from German standards.
