### ISSUE TITLE
leading language as element of report

### ISSUE THREAD

**Issue by bbube-uni** [emrex-eu/elmo-schemas#63]
Information about the original language of a report would be helpfull on client side. In international exchange it is sometimes not easy to decide which language to store in the target system. It is often requested to store original title of los/loi

**Comment by mirkostanic** [comment]
Message for EMREX executive committee: 
It is possible to determine the original language from the country of the issuing institution. It is not a 100% match but it has the same variability as other matching attributes proposed for the German education system.
Alternatively we can introduce a new boolean attribute "primary" or "original" which would be place next to langauge specification.

**Comment by mirkostanic** [comment]
Can be determined from "languageOfInstruction".
