### ISSUE TITLE
Address of issuer for German Upper Secondary School Diploma (see also #44)

### ISSUE THREAD

**Issue by GBacharach** [emrex-eu/elmo-schemas#65]
Note: This is a requirement that is part of Issue #44 and is created as a separate issue for ease of processing.

The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.

Trying to use the current ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:

Institution-specific characteristic (to be added to the “Issuer” of ELMO-structure) - **Address**

**Remarks to the additional institution-specific characteristic:**
SfH needs the address of the diploma issuer to get a unique identification of the issuer (school).

**Comment by mirkostanic** [comment]
Message for EMREX executive committee: 
Address is not a good matching attribute, for example: Erste Straße and Erste Strasse are the same address to a human but different to a machine. Also addresses change over time. In its current form addresses can be used as a best effort matching attribute and placed inside the "identifier" attribute along with PIC and SCHAC codes. We can introduce an address as an "identifier" which would not break backwards compatibility.

**Comment by GBacharach** [comment]
Sounds good. Please make a proposal for a decision for EMREX EC on how this can be implemented in ELMO.
