### ISSUE TITLE
Person-specific characteristics of the “Learner” for German Upper Secondary School Diploma (see also #44)

### ISSUE THREAD

**Issue by GBacharach** [emrex-eu/elmo-schemas#66]
Note: This is a requirement that is part of Issue #44 and is created as a separate issue for ease of processing.

Note: Is that issue already done with ELMO version 1.5???

The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.

Trying to use the current ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:

Person-specific characteristics (to be added to the “Learner” of ELMO-structure):  **Gender, placeOfBirth, birthName, address**

**Remarks to the additional person-specific characteristic:**
SfH needs the diploma learner’s

- gender, placeOfBirth, birthName and address to search and erase applicants who got more than one account in the SfH application registry (as long as there is no German eID all over)
- gender to address the applicant in digital and analogous letters
- address not to misaddress the applicant in mostly analogous letters.

With birthName the family name is meant you got as baby. After marriage family name often is changed, so you need the first family name (“birthName”) as personal identifier. Changes in first name are also possible (if someone changes his or her gender) but not so often, so that we can ignore it for the moment. 

For gender we can use ISO/IEC 5218 for the moment as used in EWP as well. In Germany we had some month ago a change in law that you are allowed to get a gender “Diverse” (not male and not female) – but that are exception, so we can ignore it for the moment (or could “9 – not applicable” used? How are other countries dealing with that?).

**Comment by mirkostanic** [comment]
Message for EMREX executive committee: 
Gender and address are not mandatory in ELMO so cannot be counted on to be present at all times.
Also, ELMO uses ISO/IEC 5218 table for gender, if this same table is not used on the German end there will be no matches. Long story short, matching on gender should be avoided.
Matching based on names and addresses can also result in a high amount of false matches, ID's should be used instead.

**Comment by GBacharach** [comment]
There is no German personal ID by now – that is the problem. As I can see PlaceOfBirth, birthname, gender and CurrentAddress are already in the current ELMO version as optional.

Am I right? In that case that issue could be closed (?).

**Comment by mirkostanic** [comment]
Yes, these elements are present, we can close this issue.
