### ISSUE TITLE
Additional certificate-specific characteristics for German Upper Secondary School Diploma (see also #44)

### ISSUE THREAD

**Issue by GBacharach** [emrex-eu/elmo-schemas#67]
Note: This is a requirement that is part of Issue #44 and is created as a separate issue for ease of processing.

The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.

Trying to use the current ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:

Certificate-specific characteristics (to be added to the “Learning Opportunity” of ELMO-structure):  s**tate-of-acquisition, country-of-acquisition, date-of-acquisition**

**Remarks to that certificate-specific characteristics:**
SfH needs the diploma learning-opportunity’s

- state-of-acquisition (German: “Bundesland des Erwerbs”) and country-of-acquisition (German: “Land des Erwerbs”) to calculate the compensation between German upper secondary school grades (“Abiturnoten-Ausgleich”)
- date-of-acquisition to
- distinguish in winter terms between applicants who already applied in former times and who applies the first time – this data is needed to calculate the date until an applicant is permitted to apply for a study program.
- calculate the waiting time in the waiting list quota.

**Remark to the date-of-acquisition:**
Does the learningOpportunityInstance/date mean the starting date when the diploma starts to be valid („The date on which the student finished studying (may contain a time zone). It doesn't necessarily need to match the end of the academic term. Preferably, this should be the date when the student has passed his final exam.”)? In that case it is exactly what we meant with “date-of-acquisition” and it can be used for that means.

**Comment by mirkostanic** [comment]
Message for EMREX executive committee: 
Date of acquisition is usually meant to represent the date of the final exam, not the date at which the diploma was generated.However this is country specific and can be defined otherwise in different jurisdictions. This is a policy question and is outside of the scope for ELMO. We cannot enforce the type of date which is placed in the field "date-of-acquisition".

**Comment by GBacharach** [comment]
In coordination with the EMREX EC, I therefore propose a solution that optionally supplements "country-of-acquisition" and "state-of-acquisition" for Germany.

Additional proposal: In order to be compatible with the German solution, such a supplement could be designed analogously to the corresponding fields in the German format XSchule (possibly with the value list that is also used there). More details (unfortunately only in German) at https://xschule.digital/web/spezifikation and in Github.

Please make a proposal for a decision on how this can be implemented in ELMO. It should also explain, why learningOpportunityInstance/date can be used as "date-of-acquisition" for Germany.

**Comment by mirkostanic** [comment]
To be solved with extensions.
