### ISSUE TITLE
Change Schema-Location of w3.org to https

### ISSUE THREAD

**Issue by MichaelLierath** [emrex-eu/elmo-schemas#69]
Hi,

I tried to generate Java code from the schema file with the maven plugin cxf-xjc-plugin. This used to work just fine, but I got an error message today: 

----
[DEBUG] MSG: http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd
[DEBUG] Severity: 2
[DEBUG] Line: 1
[DEBUG] Col: 1
[DEBUG] Vorzeitiges Dateiende.
[DEBUG] org.xml.sax.SAXParseException; systemId: http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema
.xsd; lineNumber: 1; columnNumber: 1; Vorzeitiges Dateiende.
[DEBUG] at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWra
pper.java:204)
---

I traced the reason for this error to a current experiment on the w3c website: [https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/](https://github.com/OZG-TFBildung/XBildung/issues/url)

It seems like the maven plugin is unable to follow a 307 redirect from http to https. While this redirect is temporary for now, the schema location of imported w3c schemata should be changed to the https protocol. 

Best regards
Michael

**Comment by mirkostanic** [comment]
Message for EMREX executive committee: Trivial fix.

**Comment by mirkostanic** [comment]
Fixed in V2.0
