### ISSUE TITLE
Learner personal details in multiple languages & Learner details

### ISSUE THREAD

**Issue by vmarkop** [emrex-eu/elmo-schemas#82]
In our attempts to create and enhance the eDiplomas EMREX Data Access Point, which produces ELMO XML Responses for Greek graduates, we have found some suggestions to make for the ELMO XML Schema.

1. In the current ELMO XML Schema, the Learner's Given Names and Family Name only have a single value. Ideally, we would like to store names of Greek citizens in two languages: in Greek, which is their official form, and transliterated in English using the formal standard. We propose 2 ways in which this could be achieved:

  - 1a. Multiple Given Names/ Family Name occurrences with a lang attribute
```
<learner>
    <givenNames xml:lang="en">
        Vasileios
    </givenNames>
    <givenNames xml:lang="el">
        Βασίλειος
    </givenNames>
</learner>
```
We find this to be a cleaner solution, but backwards compatibility may be an issue. We understand that Given Names / Family Name values may be used as keys for users, and it has been assumed until now that only one value exists.

  - 1b. A new, Alternative Name element, holding first name(s) and family name(s) as a single text value, but with unlimited occurrences. In this case, the English name value will remain in the givenNames / familyName elements, but alternativeName elements can hold at least one more language.
```
    <givenNames>
        Vasileios
    </givenNames>
    <familyName>
        Markopoulos
    </familyName>
    <alternativeName xml:lang="el">
        Βασίλειος Μαρκόπουλος
    </alternativeName>
</learner>
```
This version allows backwards compatibility with clients that fetch the givenNames/familyName elements and expect a single, English value.

---

2. Another issue regarding the Learner element is the lack of a description or comment free-text element. A use case example for this comment would be to include only the English, transliterated form of names in our Learner element, but explicitly disclaim that the Learner has had their names transliterated. Therefore, if our first request (1a/1b) cannot be satisfied, we would at least be complete with adding a <description> element inside the <learner> element.

Please let us know if any additional details are necessary.

Thank you,
Vasileios Markopoulos,
on behalf of GUNet.
cc @kkmanos

**Comment by mirkostanic** [comment]
Added to V2.0 preview.
