### ISSUE TITLE
Make "v1" the  default branch

### ISSUE THREAD

**Issue by wrygiel** [emrex-eu/elmo-schemas#9]
I don't have permissions to change that. Can you make "v1" the default branch?

**Comment by emrex-eu** [comment]
Maybe we should make a v1.2-branch from master and make that default branch?

**Comment by emrex-eu** [comment]
v1 is ok on second thought, since we work with backwards compatible stuff

**Comment by wrygiel** [comment]
> v1 is ok on second thought, since we work with backwards compatible stuff

Yes. Also, the existing XML namespace refers to it.
