### ISSUE TITLE
Temporary reintroduction of learner.bday in ELMO2.1

### ISSUE THREAD

**Issue by geirmv** [emrex-eu/elmo-schemas#90]
**Meeting 28 June (Tor, Mirko, Jan-Joost, Geir)**

The change of bday to dateOfBirth in ELMO2.0 makes it difficult to upgrade from ELMO1.x for EMREX EMC's. The reason is the use of bday in clients for complare user autentications between EMC and EMP.

I would propose a temporary reintroduction of learner.bday in ELMO2.1 to facilitate transition to ELMO2x without the need of changing all EMREX clients. The element can be set up as obselete, but it enables EMPs for some time deliver both bday and dateOfBirth for learner.

```
                            <xs:element minOccurs="0" name="bday" type="xs:date">
                                <xs:annotation>
                                    <xs:documentation>For server implementers: The birth date is vital to EMREX and SHOULD be provided.
                                        If you cannot provide it, you MUST skip the bday element altogether.

                                        This data element is obselete, and has been replaces with dateOfBirth. Providers of EMPs should for some
                                        time provide both bday and dataOfBirth to support EMCs that has not upgraded to ELMO2x yet.
                                        Providers of EMCs should only user dateOfBirth after upgradering to ELMO2.x
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

```

**Comment by mathjert** [comment]
Solved in ELMO 2.1 https://github.com/emrex-eu/elmo-schemas/pull/96
