### ISSUE TITLE
Add NQF to documentation of level

### ISSUE THREAD

**Issue by geirmv** [emrex-eu/elmo-schemas#92]
**Meeting 28 June (Tor, Mirko, Jan-Joost, Geir)**

EQF (European Qualification Framework) is mentioned as a type of level that can be delivered by ELMO. 

Introduction of OOTS and the EMREX-OOTS bridge also includes NQF (National Qualification Framework) in the description of data elements needed for education processes.

Level in ELMO is not restricted to a certain list of types, but has a description on the use of this element.

We propose to add 
"- NQF (National Qualification Framework)"
to the documentation, in addition to EQF.

**Comment by mathjert** [comment]
Solved in ELMO 2.1 https://github.com/emrex-eu/elmo-schemas/pull/98
