### ISSUE TITLE
Add identifier to ResultsOfRecognition

### ISSUE THREAD

**Issue by bbube-uni** [emrex-eu/elmo-schemas#93]
On German Platform for inter*national student mobility (PIM) (https://www.pim-plattform.de/en) recognitions are the result of a digital workflow. Recognition decisions are transferred to other digital systems as campus management systems. To identify recognition uniquely between those systems, we need to supply identifiers. Additionally as maxOccurs of ResultsOdRecognition is unbound, it would be necessary to differentiate those nodes. Title is not suitable for this task.

So we suggest to add identifier to ResultsOfRecognition similiar to LearningOpportunitySpecification.identifier.

**Comment by mathjert** [comment]
Solved in ELMO 2.1 https://github.com/emrex-eu/elmo-schemas/pull/99
